create table
  public.authors (
    auth_id uuid not null,
    user_type boolean not null default false,
    email text null,
    constraint users_pkey primary key (auth_id),
    constraint authors_auth_id_fkey foreign key (auth_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;

create table
  public.comments (
    id bigint generated by default as identity,
    user_id uuid null,
    post_id bigint null,
    created_at timestamp with time zone not null default now(),
    text text null,
    commenter_email text null,
    constraint comments_pkey primary key (id),
    constraint comments_post_id_fkey foreign key (post_id) references posts (id) on delete cascade,
    constraint comments_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;

create table
  public.countries (
    id serial,
    name text not null,
    constraint countries_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.posts (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    user_id uuid null,
    title text null,
    text text null,
    author_email text null,
    constraint posts_pkey primary key (id),
    constraint posts_user_id_fkey foreign key (user_id) references authors (auth_id) on delete cascade
  ) tablespace pg_default;
  